version: "2.4"

volumes:
  postgres_data:
  app_node_modules: # Used to store the app's node modules...

networks:
  backend:

services:
  postgres:
    image: postgres:10.6-alpine
    volumes:
    # We'll store the postgres data in the 'postgres_data' volume we defined:
    - postgres_data:/var/lib/postgresql/data
    networks:
    - backend
    environment:
      POSTGRES_PASSWORD: 3x4mpl3P455w0rd

  # The job processor container - we'll use this as a base for the rest of the
  # containers:
  test: &app
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: icalialabs/library_backend:development
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    volumes:
      # Mount the app code into the app containers at the "/usr/src" folder:
      - .:/usr/src

      # After mounting the app code, this replaces the local 'node_modules'
      # folder inside the container with a Docker volume. This is done for
      # several reasons:
      # - So we can run the frontend app either from the host (i.e. macOS) or
      #   using containers without having the host & container clobber the npm
      #   each other's packages, or avoid conflicting versions for macOS / Linux
      # - Helps when running on macOS/Windows to speed up the npm install from,
      #   zero, since a local volume bind on mac/win is noticeably slower than
      #   a Docker volume - and node module install is very susceptible to
      #   I/O performance
      - app_node_modules:/usr/src/node_modules
    networks:
      - backend

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true

    # Link to our postgres and redis containers, so they can be visible from our
    # app containers:
    depends_on:
    - postgres

    # The command we want to execute by default when running the container
    command: rspec

    # Specify environment variables available for our app containers. We'll leave
    # a YML anchor in case we need to override or add more variables if needed on
    # each app container:
    environment: &app_environment
      # We'll set the DATABASE_URL environment variable for the app to connect
      # to our postgres container - no need to use a 'config/database.yml' file.
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/library_backend_test

      # We'll set the RAILS_ENV and RACK_ENV environment variables to
      # 'development', so our app containers will start in 'development' mode
      # on this compose project:
      RAILS_ENV: test
      RACK_ENV: test
      RAILS_LOG_TO_STDOUT: "true"
      MAILER_HOST: localhost
      MAILER_PORT: 3000
      LISTEN_USE_POLLING: ${PROJECT_NAME_LISTEN_USE_POLLING:-no}

  web:
    <<: *app
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - ${LIBRARY_BACKEND_WEB_PORT:-3000}:3000
    environment:
      <<: *app_environment
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/library_backend_development
      RAILS_ENV: development
      RACK_ENV: development
      WEBPACKER_HOST: webpacker
    depends_on:
    - webpacker
    - postgres
  
  migration:
    <<: *app
    command: rails db:migrate
    ports:
      - ${LIBRARY_BACKEND_WEB_PORT:-3001}:3001
    environment:
      <<: *app_environment
      DATABASE_URL: postgres://postgres:3x4mpl3P455w0rd@postgres:5432/library_backend_development
      RAILS_ENV: development
      RACK_ENV: development
    depends_on:
    - postgres

  # This container autocompiles, serves and live-reloads Webpack assets
  # (including our ReactJS code) for our development environment. This service
  # is proxied by the `web` container, so there is no need to publish ports for
  # it:
  webpacker:
    <<: *app
    ports:
    - ${LIBRARY_BACKEND_WEBPACKER_DEV_SERVER_PORT:-3035}:3035
    command: webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      RAILS_ENV: development